services:
  - type: web
    name: asm-store
    env: php
    plan: free
    region: frankfurt
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build
    startCommand: php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql